name: Pull Request CI Check
on: [pull_request]
jobs:
  build:
    name: Run CI
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.20.3
        id: go
      - name: Check out the code
        uses: actions/checkout@v2
      - name: Fetch cached go modules
        uses: actions/cache@v2
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: Make ci
        run: make ci
      - name: Upload test coverage
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: coverage.out
          verbose: true
